# Generated by Django 3.1.2 on 2020-10-31 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accounting_card', models.CharField(blank=True, max_length=300, null=True, verbose_name='Карточка учета животного')),
                ('kind', models.CharField(blank=True, max_length=30, null=True, verbose_name='Вид')),
                ('age', models.CharField(blank=True, max_length=300, null=True, verbose_name='Возраст, год')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='вес, кг')),
                ('animal_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Кличка')),
                ('sex', models.CharField(blank=True, max_length=10, null=True, verbose_name='Пол')),
                ('breed', models.CharField(blank=True, max_length=30, null=True, verbose_name='Порода')),
                ('colour', models.CharField(blank=True, max_length=300, null=True, verbose_name='Окрас')),
                ('wool', models.CharField(blank=True, max_length=300, null=True, verbose_name='Шерсть')),
                ('ears', models.CharField(blank=True, max_length=300, null=True, verbose_name='Уши')),
                ('tail', models.CharField(blank=True, max_length=300, null=True, verbose_name='Хвост')),
                ('size', models.CharField(blank=True, max_length=300, null=True, verbose_name='Размер')),
                ('features', models.CharField(blank=True, max_length=300, null=True, verbose_name='Особые размеры')),
                ('aviary', models.CharField(blank=True, max_length=300, null=True, verbose_name='Вольтер №')),
                ('id_label', models.CharField(blank=True, max_length=300, null=True, verbose_name='Идентификационная метка')),
                ('sterilization_date', models.CharField(blank=True, max_length=300, null=True, verbose_name='Дата стерилизации')),
                ('doctor_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='ф.и.о. ветеринарного врача')),
                ('is_socialized', models.BooleanField(blank=True, null=True, verbose_name='Социализировано')),
                ('admission_info', models.CharField(blank=True, max_length=300, null=True, verbose_name='Заказ-наряд / Акт о поступлении животного №')),
                ('admission_date', models.CharField(blank=True, max_length=300, null=True, verbose_name='заказ-наряд дата/ акт о поступлении животного, дата')),
                ('district', models.CharField(blank=True, max_length=10, null=True, verbose_name='Административный округ')),
                ('capture_act', models.CharField(blank=True, max_length=300, null=True, verbose_name='акт отлова №')),
                ('capture_address', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Адрес места отлова')),
                ('entity', models.CharField(blank=True, max_length=300, null=True, verbose_name='Юридическое лицо')),
                ('guardian_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='ф.и.о. опекунов')),
                ('individual', models.CharField(blank=True, max_length=300, null=True, verbose_name='Физическое лицо ф.и.о.')),
                ('issued', models.BooleanField(blank=True, default=False, null=True, verbose_name='Выдано')),
                ('receipts_date', models.CharField(blank=True, max_length=300, null=True, verbose_name='Дата поступления в приют')),
                ('act_number', models.CharField(blank=True, max_length=300, null=True, verbose_name='Акт №')),
                ('departure_date', models.CharField(blank=True, max_length=300, null=True, verbose_name='Дата убытия из приюта')),
                ('departure_reason', models.CharField(blank=True, max_length=300, null=True, verbose_name='Причина убытия')),
                ('contract_number', models.CharField(blank=True, max_length=300, null=True, verbose_name='Акт/Договор №')),
                ('shelter_address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Адрес приюта')),
                ('operating_organization', models.CharField(blank=True, max_length=300, null=True, verbose_name='Эксплуатирующая организация')),
                ('shelter_director', models.CharField(blank=True, max_length=300, null=True, verbose_name='ф.и.о. руководителя приюта')),
                ('сare_person', models.CharField(blank=True, max_length=300, null=True, verbose_name='ф.и.о. сотрудника по уходу за животным')),
                ('trearment_date', models.CharField(blank=True, max_length=300, null=True, verbose_name='Дата обращения')),
                ('preparation_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Название препарата')),
                ('dose', models.CharField(blank=True, max_length=300, null=True, verbose_name='Доза')),
                ('vaccination_info', models.CharField(blank=True, max_length=300, null=True, verbose_name='Вид вакцины')),
                ('vaccination_date', models.CharField(blank=True, max_length=300, null=True, verbose_name='Дата вакцинации')),
                ('serie_number', models.CharField(blank=True, max_length=300, null=True, verbose_name='№ серии')),
                ('inspection_date', models.DateField(blank=True, null=True, verbose_name='Дата осмотра')),
                ('anamnesis', models.CharField(blank=True, max_length=300, null=True, verbose_name='Анамнез')),
            ],
            options={
                'verbose_name': 'животное',
                'verbose_name_plural': 'животные',
                'ordering': ['-id'],
            },
        ),
    ]
