# Generated by Django 3.1.2 on 2020-10-31 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='inspection_date',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Дата осмотра'),
        ),
    ]
