# Generated by Django 3.1.2 on 2020-11-01 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_auto_20201031_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='animals',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='animals',
            name='issued',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Выдано'),
        ),
    ]
